### ISSUE TITLE
BC break with v 2.5.0

### ISSUE THREAD

**Issue by RadekDvorak** [sarulabs/di#35]
Hi,

the v2.5.0 causes compilation failures for [sarulabs/dingo](https://github.com/sarulabs/dingo) 4.2.0.

```
di/dic/container.go:145:31: invalid operation: p != nil (mismatched types di.Container and untyped nil)
```

The relevant code there in dingo is:
```golang
// Parent returns the parent Container.
func (c *Container) Parent() *Container {
	if p := c.ctn.Parent(); p != nil {
		return &Container{ctn: p}
	}
	return nil
}
```

Parent is no longer an interface. I guess it is an unexpected consequence as the di v2.5.0 release claims it "stays compatible with the previous version".

**Comment by sarulabs** [comment]
Hello,

I wrote the code 2 years ago but only released it yesterday. I did not remember that I changed the type of `Container`. I will change the release notes.

It should not have been an issue as the name of the type is the same. The reason it does not work in the generated code is because the `Parent` method is flawed.

I used it as it could return `nil`, but it never does that. Instead it returns a broken container.

I'm going to leave the `Parent` method as it is and create a new `ParentContainer` method that also returns an error. The first one would be removed from the documentation.

I will also have to update dingo as there is no way it can work with the new di versions as it is. I will check if I can use the `Parent` method instead of the new one. It would make it compatible with the old di versions.

I will work on it this weekend.

**Comment by sarulabs** [comment]
The issue should be fixed.

You need to update dingo to v4.2.1 and di to v2.5.1

**Comment by danilNikolaenko1990** [comment]
Hello, @sarulabs 
Unfortunately it seems the issue is still not fixed.
I updated the dependencies to the latest versions:
```
github.com/sarulabs/di/v2 v2.5.2
github.com/sarulabs/dingo/v4 v4.2.1
```
but the project still fails to compile with the following error:
```
src/infra/dic/gen/dic/container.go:141:31: invalid operation: p != nil (mismatched types di.Container and untyped nil)
make: *** [build] Error 1
```
The error happens in the generated code:
`// Parent returns the parent Container.
func (c *Container) Parent() *Container {
	if p := c.ctn.Parent(); p != nil {
		return &Container{ctn: p}
	}
	return nil
}`
It looks like ctn.Parent() now returns di.Container (a concrete type), so the comparison p != nil is no longer valid.
Could you please confirm if this combination of versions (di v2.5.x + dingo v4.2.x) is expected to work, or if additional changes are required?

**Comment by sarulabs** [comment]
Hello,
the code where the error happens does not look like dingo `v4.2.1`
https://github.com/sarulabs/dingo/blob/v4.2.1/templates/container.tmpl.go#L142
I think your issue is that dingo is not up to date. You probably use `v4.2.0`.
